'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2407.
'
Namespace agraf_lt2
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ItfCollectionsSoap", [Namespace]:="http://tempuri.org/YSI.Interfaces.WebServices/ItfCollections")>  _
    Public Class ItfCollections
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://agraf-lt2/Webservices/ItfCollections.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YSI.Interfaces.WebServices/ItfCollections/Get_CollectionsLease"& _ 
"Info", RequestNamespace:="http://tempuri.org/YSI.Interfaces.WebServices/ItfCollections", ResponseNamespace:="http://tempuri.org/YSI.Interfaces.WebServices/ItfCollections", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_CollectionsLeaseInfo(ByVal UserName As String, ByVal Password As String, ByVal ServerName As String, ByVal Database As String, ByVal Platform As String, ByVal CollectionsAgency As String, ByVal YardiPropertyId As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_CollectionsLeaseInfo", New Object() {UserName, Password, ServerName, Database, Platform, CollectionsAgency, YardiPropertyId})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginGet_CollectionsLeaseInfo(ByVal UserName As String, ByVal Password As String, ByVal ServerName As String, ByVal Database As String, ByVal Platform As String, ByVal CollectionsAgency As String, ByVal YardiPropertyId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Get_CollectionsLeaseInfo", New Object() {UserName, Password, ServerName, Database, Platform, CollectionsAgency, YardiPropertyId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGet_CollectionsLeaseInfo(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YSI.Interfaces.WebServices/ItfCollections/Ping", RequestNamespace:="http://tempuri.org/YSI.Interfaces.WebServices/ItfCollections", ResponseNamespace:="http://tempuri.org/YSI.Interfaces.WebServices/ItfCollections", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Ping() As String
            Dim results() As Object = Me.Invoke("Ping", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginPing(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Ping", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndPing(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
